properties([disableConcurrentBuilds()])

pipeline {
  	agent {label ""}
		options {
			buildDiscarder(logRotator(numToKeepStr: '10'))
			timestamps()
		}
		stages {
			stage("test1"){
				steps {
					sh "ls -la"
					}
				}
			stage("test2") {
				steps {
					sh "echo 'hello world' > text.txt"
					sh "ls -la && cat text.txt"
				}
			}	
		}
	}

