properties([disableConcurrentBuilds()])

pipeline {
	agent {
		docker {
			image "python:latest"
			args "--user root"
		}
	}
	environment { 
        USERNAME = 'edo1997edo'
    }

	stages {
		stage("pylint test") {
			steps {
			  echo "========== pylint test =========="
				sh "ls -la"
				sh "pip install pylint"
				sh "pylint pipe3/app.py  --fail-under=4.0"
			}
		}
		stage("build docker image") {
			steps{
			  echo "========== building Docker image =========="
				sh "docker build -t $USERNAME/jenkins-pylint-test:v1 ./pipe3/"
				sh "docker run  --rm  --name jenkins_test  $USERNAME/jenkins-pylint-test:v1"
				sh "docker images"
				}
			}
		stage("login Docker Hub") {
			steps {
				echo "========== docker login =========="
				withCredentials([usernamePassword(credentialsId:'loging_docker_hub',usernameVariable: 'USERNAME',passwordVariable: 'PASSWORD')]) {
						sh "docker login -u $USERNAME -p $PASSWORD"
					}
				}
			}
		stage("push Docker Hub") {
			steps {
				echo "========== start pushing image =========="
				sh "docker push $USERNAME/jenkins-pylint-test:v1"
				}
			}
		}
	}
