pipeline {
	agent {
		docker {
			image "python:latest"
			args "--user root"
		}
	}
	stages {
		stage("pylint test") {
			steps{
				sh "ls -la"
				sh "pip install pylint"
				sh "pylint pipe3/app.py"
			}
		}
	}
}
